name: OnePlus 8T

on:
  push:
  workflow_dispatch:
    inputs:
      add_kernelsu:
        description: "Add KernelSU"
        type: boolean
        required: true
        default: false

jobs:
  build:
    runs-on: ubuntu-24.04
    container:
      image: pexcn/docker-images:bookworm-android
    env:
      TZ: Asia/Taipei
      BUILD_CONFIG: nameless-14
      ENABLE_FEATURE: ${{ github.event.inputs.enable_feature || false }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Show Checkbox Selection
        run: |
          if [[ "$ENABLE_FEATURE" == "true" ]]; then
            echo "Feature is ENABLED"
          else
            echo "Feature is DISABLED"
          fi

      - name: Build
        run: |
          chmod +x build.sh
          ./build.sh
