name: OnePlus 8T

on:
  push:
  workflow_dispatch:
    inputs:
      add_kernelsu:
        description: "Add KernelSU"
        type: boolean
        required: true
        default: true

jobs:
  build:
    runs-on: ubuntu-24.04
    #container:
    #  image: pexcn/docker-images:bookworm-android
    env:
      TZ: Asia/Taipei
      BUILD_CONFIG: nameless-14
      ADD_KERNELSU: ${{ github.event.inputs.add_kernelsu }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Build
        run: |
          chmod +x build.sh
          ./build.sh
