name: OnePlus 8T

on:
  push:
  workflow_dispatch:
    inputs:
      add_kernelsu:
        description: "Add KernelSU"
        type: boolean
        required: true
        default: true
      upload_release:
        description: 'Upload to Releases'
        type: boolean
        required: true
        default: false

jobs:
  build:
    runs-on: ubuntu-24.04
    #container:
    #  image: pexcn/docker-images:bookworm-android
    env:
      TZ: Asia/Taipei
      BUILD_CONFIG: nameless-14
      ADD_KERNELSU: ${{ github.event.inputs.add_kernelsu }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Build
        run: |
          chmod +x build.sh
          ADD_KERNELSU=false
          ./build.sh

      - name: Upload to Releases
        if: github.event_name == 'push' && startsWith(github.event.head_commit.message, '[release] ') || github.event.inputs.upload_release == true
        uses: softprops/action-gh-release@v2
        with:
          tag_name: test
          files: build.sh
