name: Test

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04
    container:
      image: pexcn/docker-images:bookworm-android
    env:
      TZ: Asia/Taipei

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Fix
        run: |
          sudo apt update
          sudo apt install -y openssh-client
          mkdir ~/.ssh
          touch ~/.ssh/id_rsa

      - name: Start SSH via tmate
        uses: P3TERX/ssh2actions@main
