name: Build

on:
  push:
    paths-ignore:
      - 'ext/**'
      - '**.md'
      - '**/docker-compose.yml'
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Whether to deploy DockerHub and GHCR'
        required: true
        default: '0'

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    env:
      TZ: Asia/Taipei
    strategy:
      fail-fast: false
      matrix:
        include:
          # openjdk-7
          - BUILD_CONTEXT: java/openjdk-7
            TARGET_PLATFORMS: linux/amd64,linux/arm64

    steps:
      # prepare
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set environment variables
        run: |
          echo "BUILD_TAG=$(basename ${{ matrix.BUILD_CONTEXT }})" >> $GITHUB_ENV

      # login
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      # build & push
      - name: Build image and Push to Container Registries
        uses: docker/build-push-action@v5
        if: ${{ github.event_name == 'push' || github.event.inputs.deploy == '1' }}
        with:
          context: ${{ matrix.BUILD_CONTEXT }}
          tags: |
            ghcr.io/${{ github.repository }}:${{ env.BUILD_TAG }}
          platforms: ${{ matrix.TARGET_PLATFORMS }}
          push: true
