name: Test

on: push


jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: pexcn/docker-images:buster-openwrt
      options: --user builder
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: chmod +x ./test.sh && ./test.sh
