name: CI

on:
  push:

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    env:
      TZ: Asia/Taipei
    strategy:
      fail-fast: false
      matrix:
        include:
          # shadowsocks-rust
          - BUILD_CONTEXT: net/shadowsocks-rust
            TARGET_PLATFORMS: linux/amd64

    steps:
      # prepare
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set environment variables
        run: |
          echo "BUILD_TAG=$(basename ${{ matrix.BUILD_CONTEXT }})" >> $GITHUB_ENV

      ## login
      #- name: Login to GitHub Container Registry
      #  uses: docker/login-action@v2
      #  with:
      #    registry: ghcr.io
      #    username: ${{ github.repository_owner }}
      #    password: ${{ secrets.GHCR_PAT }}

      # build & push
      - name: Build image and Push to Container Registries
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.BUILD_CONTEXT }}
          platforms: ${{ matrix.TARGET_PLATFORMS }}
