name: Test

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    #container:
    #  image: pexcn/docker-images:bookworm-android
    env:
      TZ: Asia/Taipei

    steps:
      - name: Set environment variable using `env`
        env:
          BUILD_DATE: "${{ runner.os == 'Linux' && '$(/bin/date +%Y%m%d)' || 'fallback' }}"
        run: echo "The build date is $BUILD_DATE"
