name: Build

on:
  push:
  workflow_dispatch:
    inputs:
      upload_release:
        description: 'Whether to upload binaries to releases'
        required: true
        default: '0'

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      TZ: Asia/Taipei
      TEST: TEST_STRING

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        # with:
        #   submodules: true

      # - name: Start SSH session
      #   uses: luchihoratiu/debug-via-ssh@main
      #   with:
      #     NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      #     SSH_PASS: ${{ secrets.SSH_PASS }}

      # - name: Maximize build space
      #   uses: pexcn/maximize-build-space@master

      - name: Run
        #continue-on-error: true
        run: |
          sudo apt-get update
          sudo apt-get install rename -y

          mkdir -p openwrt/bin/targets/qualcommax/ipq60xx
          cd openwrt/bin/targets/qualcommax/ipq60xx
          echo test > openwrt-sdk-qualcommax-ipq60xx_gcc-12.3.0_musl.Linux-x86_64.tar.zst
          cd -
          rename "s/qualcommax-ipq60xx/${{ env.BUILD_PROFILE }}/" openwrt/bin/targets/*/*/openwrt-sdk-*.tar.zst

      - name: Upload to Releases
        #if: (github.event_name == 'push' && startsWith(github.event.head_commit.message, '[release] ')) || (github.event.inputs.upload_release == 1)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            test*.tar.gz
            openwrt/bin/targets/*/*/openwrt-sdk-*.tar.xz
