name: Test

on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: pexcn/docker-images:buster-openwrt
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        #if: "!startsWith(github.event.head_commit.message, 'WIP')"
        run: |
          echo ${{ github.event.head_commit.message }}
