name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'ext/**'
      - '**.md'
      - '**/docker-compose.yml'
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Whether to deploy DockerHub and GHCR'
        required: true
        default: '0'

jobs:
  build-and-push:
    #if: "!startsWith(github.event.head_commit.message, 'ext:')"
    runs-on: ubuntu-22.04
    env:
      TZ: Asia/Taipei
    strategy:
      fail-fast: false
      matrix:
        include:
          # shadowsocks-rust
          - BUILD_CONTEXT: net/shadowsocks-rust
            TARGET_PLATFORMS: linux/amd64,linux/arm64

    steps:
      # prepare
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set environment variables
        run: |
          echo "BUILD_TAG=$(basename ${{ matrix.BUILD_CONTEXT }})" >> $GITHUB_ENV

      # cache
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-${{ env.BUILD_TAG }}-buildx-${{ github.sha }}
          restore-keys: ${{ runner.os }}-${{ env.BUILD_TAG }}-buildx-

      # build & push
      - name: Build image and Push to Container Registries
        uses: docker/build-push-action@v3
        if: ${{ github.event_name == 'push' || github.event.inputs.deploy == '1' }}
        with:
          context: ${{ matrix.BUILD_CONTEXT }}
          tags: |
            ${{ github.repository }}:${{ env.BUILD_TAG }}
            ghcr.io/${{ github.repository }}:${{ env.BUILD_TAG }}
          platforms: ${{ matrix.TARGET_PLATFORMS }}
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
