name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: pexcn/docker-images:buster-openwrt
      #options: --user root --privileged
      volumes:
        - /usr/local/lib/android:/usr/local/lib/android
        - /usr/share/dotnet:/usr/share/dotnet
        - /opt/ghc:/opt/ghc
        - /opt/hostedtoolcache/CodeQL:/opt/hostedtoolcache/CodeQL
        - /var/run/docker.sock:/var/run/docker.sock
    env:
      TZ: Asia/Taipei
      BUILD_PROFILE: ${{ matrix.PROFILE }}
    strategy:
      fail-fast: false
      matrix:
        PROFILE:
          - ipq60xx-generic

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Run
        run: |
          df -Th

      - name: Maximize build space
        run: |
          export DOCKER_VERSION=24.0.2
          case "$(dpkg --print-architecture)" in \
            amd64) arch="x86_64";; \
            *) arch="aarch64";; \
          esac && curl https://download.docker.com/linux/static/stable/${arch}/docker-${DOCKER_VERSION}.tgz | \
            tar zxv -C /usr/local/bin/ docker/docker --strip-components 1
          sudo find /usr/local/lib/android -mindepth 1 -delete
          sudo find /usr/share/dotnet -mindepth 1 -delete
          sudo find /opt/ghc -mindepth 1 -delete
          sudo find /opt/hostedtoolcache/CodeQL -mindepth 1 -delete
          docker ps -a || true
          docker image ls || true
          docker container ls || true
          docker volume ls || true
          docker network ls || true
          docker image prune -af || true
          docker container prune -f || true
          docker volume prune -f || true

      - name: Run
        run: |
          df -Th

      - name: Upload to Releases
        if: github.event_name == 'push'
        uses: softprops/action-gh-release@v1
        with:
          #name:
          tag_name: ${{ github.ref_name }}
          files: ${{ env.BUILD_PROFILE }}.tar.gz
          #generate_release_notes: true
