name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: pexcn/docker-images:buster-openwrt
      options: --user root --privileged
    env:
      TZ: Asia/Taipei
      BUILD_PROFILE: ${{ matrix.PROFILE }}
    strategy:
      fail-fast: false
      matrix:
        PROFILE:
          - ipq60xx-generic

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Run
        run: |
          df -Th

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Run
        run: |
          df -Th

      - name: Upload to Releases
        if: github.event_name == 'push'
        uses: softprops/action-gh-release@v1
        with:
          #name:
          tag_name: ${{ github.ref_name }}
          files: ${{ env.BUILD_PROFILE }}.tar.gz
          #generate_release_notes: true
