name: Release

on:
  release:
    types: [released]
  workflow_dispatch:
    inputs:
      TAG_NAME:
        description: 'Tag name that the major tag will point to'
        required: true

#permissions:
#  contents: write

jobs:
  update_tag:
    name: Update the major tag
    runs-on: ubuntu-latest
    env:
      TAG_NAME: ${{ github.event.inputs.TAG_NAME || github.event.release.tag_name }}
    steps:
      - name: Update the ${{ env.TAG_NAME }} tag
        uses: actions/publish-action@v0.2.2
        with:
          source-tag: ${{ env.TAG_NAME }}
