name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: pexcn/docker-images:buster-openwrt
    env:
      TZ: Asia/Taipei
      BUILD_PROFILE: ${{ matrix.PROFILE }}
    strategy:
      fail-fast: false
      matrix:
        PROFILE:
          - ipq60xx-generic

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Run
        run: |
          echo $(date) > $BUILD_PROFILE

      - name: Upload to Releases
        if: github.event_name == 'push'
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.GITHUB_REF_NAME }}
          allowUpdates: true
          artifacts: ${{ env.BUILD_PROFILE }}.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}
