name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: pexcn/docker-images:buster-openwrt
      #options: --user root --privileged
      volumes:
        - /usr/local/lib/android:/usr/local/lib/android
        - /usr/share/dotnet:/usr/share/dotnet
        - /opt/ghc:/opt/ghc
        - /opt/hostedtoolcache/CodeQL:/opt/hostedtoolcache/CodeQL
    env:
      TZ: Asia/Taipei
      BUILD_PROFILE: ${{ matrix.PROFILE }}
    strategy:
      fail-fast: false
      matrix:
        PROFILE:
          - ipq60xx-generic

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Run
        run: |
          df -Th

      - name: Maximize build space
        run: |
          sudo rm -rf /usr/local/lib/android /usr/share/dotnet /opt/ghc /opt/hostedtoolcache/CodeQL

      - name: Run
        run: |
          df -Th

      - name: Upload to Releases
        if: github.event_name == 'push'
        uses: softprops/action-gh-release@v1
        with:
          #name:
          tag_name: ${{ github.ref_name }}
          files: ${{ env.BUILD_PROFILE }}.tar.gz
          #generate_release_notes: true
