name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: pexcn/docker-images:buster-openwrt
    env:
      TZ: Asia/Taipei

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run build
        run: |
          df -h
          free -h
