name: CI

on:
  push:
    branches: master
  release:
    types: published
  workflow_dispatch:

env:
  TZ: Asia/Taipei

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: pexcn/docker-images:buster-openwrt
      #options: --user builder
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run build
        run: df -h
