name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: pexcn/docker-images:buster-openwrt
    env:
      TZ: Asia/Taipei
      BUILD_PROFILE: ${{ matrix.PROFILE }}
    strategy:
      fail-fast: false
      matrix:
        PROFILE:
          - ipq60xx-generic

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Run
        run: |
          echo $GITHUB_BASE_REF
          echo $GITHUB_HEAD_REF
          echo $GITHUB_REF
          echo $GITHUB_REF_NAME
