name: Build

on:
  push:
  workflow_dispatch:
    inputs:
      upload_release:
        description: 'Whether to upload binaries to releases'
        required: true
        default: '0'

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      TZ: Asia/Taipei
      TEST: ${{ github.event.inputs.upload_release }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        # with:
        #   submodules: true

      - name: Start SSH session
        uses: luchihoratiu/debug-via-ssh@main
        with:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
          SSH_PASS: ${{ secrets.SSH_PASS }}

      # - name: Maximize build space
      #   uses: pexcn/maximize-build-space@master

      - name: Run
        #continue-on-error: true
        run: bash test.sh

      # - name: Upload to Releases
      #   if: (github.event_name == 'push' && startsWith(github.event.head_commit.message, '[release] ')) || (github.event.inputs.upload_release == 1)
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     tag_name: ${{ github.ref_name }}
      #     files: ${{ env.BUILD_PROFILE }}.tar.gz
