name: CI

on:
  push:
    branches: master
  release:
    types: published
  workflow_dispatch:

env:
  TZ: Asia/Taipei

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: pexcn/docker-images:buster-openwrt
      #options: --user builder
    steps:
      - name: Run build
        run: |
          df -h
          apt-get install procps 

      - name: Checkout
        uses: actions/checkout@v2

      - name: Free Up More Space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 256
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          overprovision-lvm: 'true'

      - name: Run build
        run: df -h
