name: CI

on:
  push:
    branches: master
  release:
    types: published
  workflow_dispatch:

env:
  TZ: Asia/Taipei

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: rust:alpine
      #options: --user builder
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run build
        run: ./build.sh
      - name: Upload to Artifact
        uses: actions/upload-artifact@v2
        with:
          name: tarball
          path: shadowsocks-rust/target/release
