name: Build

on:
  push:
  workflow_dispatch:
    inputs:
      upload_release:
        description: 'Whether to upload binaries to releases'
        required: true
        default: '0'

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: pexcn/docker-images:buster-openwrt
    env:
      TZ: Asia/Taipei
      BUILD_PROFILE: ${{ matrix.PROFILE }}
    strategy:
      fail-fast: false
      matrix:
        PROFILE:
          - ipq60xx-generic

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Run
        run: |
          df -h > ${BUILD_PROFILE}.tar.gz

      - name: Upload to Releases
        #if: (github.event_name == 'push' && startsWith(github.event.head_commit.message, '[release] ')) || (github.event.inputs.upload_release == 1)
        uses: softprops/action-gh-release@v1
        with:
          #body: test
          target_commitish: ${{ github.job_workflow_sha }}
          append_body: true
          tag_name: ${{ github.ref_name }}
          files: ${{ env.BUILD_PROFILE }}.tar.gz
